"""empty message

Revision ID: 0687a3eabd47
Revises: 
Create Date: 2024-02-13 12:18:04.178428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0687a3eabd47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('author', sa.Column('country', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'country')
    op.drop_column('author', 'birth_date')
    # ### end Alembic commands ###
